### ISSUE TITLE
tensor.sources.rabbitmq doesn't detect last queue in list_queues

### ISSUE THREAD

**Issue by sashavoz** [calston/tensor#16]
It seems that the last queue name in the alphabetically sorted list of queues doesn't make it into metrics sent to Riemann. 

e.g. with queues named:
aaaa
bbbb
cccc
dddd

'dddd' metrics will not appear in the outputs. However they will, if you add 'eeee', in which case 'eeee' won't be appearing.

**Comment by calston** [comment]
Which version of RabbitMQ does that happen with?

**Comment by sashavoz** [comment]
RabbitMQ version 3.4.2, running on Raspbian (Linux version 3.12.32+ (dc4@dc4-XPS13-9333) (gcc version 4.8.3 20140303 (prerelease) (crosstool-NG linaro-1.13.1+bzr2650 - Linaro GCC 2014.03) ) #721 PREEMPT Fri Nov 7 16:50:31 GMT 2014)
